### ISSUE TITLE
TypeError: Cannot read property 'pipesCount' of undefined

### ISSUE THREAD

**Issue by jhurliman** [nfriedly/node-bestzip#6]
```
Writing index.js, package.json, node_modules to package.zip...
_stream_readable.js:545
  switch (state.pipesCount) {
               ^

TypeError: Cannot read property 'pipesCount' of undefined
    at module.exports.Readable.pipe (_stream_readable.js:545:16)
    at module.exports.ZipArchiveOutputStream._smartStream (.../node_modules/compress-commons/lib/archivers/zip/zip-archive-output-stream.js:171:11)
    at module.exports.ZipArchiveOutputStream._appendStream (.../node_modules/compress-commons/lib/archivers/zip/zip-archive-output-stream.js:94:20)
    at module.exports.ArchiveOutputStream.entry (.../node_modules/compress-commons/lib/archivers/archive-output-stream.js:89:10)
    at module.exports.ZipStream.entry (.../node_modules/zip-stream/lib/zip-stream.js:105:49)
    at Zip.append (.../node_modules/archiver/lib/plugins/zip.js:40:15)
    at Archiver._moduleAppend (.../node_modules/archiver/lib/core.js:166:16)
    at Archiver._onQueueTask (.../node_modules/archiver/lib/core.js:356:8)
    at .../node_modules/archiver/node_modules/async/lib/async.js:987:13
    at Immediate.process [as _onImmediate] (.../node_modules/archiver/node_modules/async/lib/async.js:953:21
```

**Comment by jhurliman** [comment]
Upgrading node from 8.0.0 to 8.2.1 fixed this.
